// apps/web/src/components/wizard/StepTestPublish.vue
<script setup lang="ts">
import { computed } from 'vue'
import { agentsApi } from '@/api/agents'
import { useWizardStore } from '@/stores/wizard'
import AgentChatWidget from '@/components/AgentChatWidget.vue'

const props = defineProps<{ agentId: string | null }>()
const emit = defineEmits<{ publish: [status: 'draft' | 'published' | 'submitted'] }>()

const wizard = useWizardStore()

const isValid = computed(
  () => wizard.draft.config.name.trim().length > 0 && wizard.draft.config.system_prompt.trim().length > 0,
)

const visibilityLabel = computed(() => {
  const v = wizard.draft.visibility
  if (v === 'private') return 'Privé'
  if (v === 'community') return `Communauté ${wizard.draft.config.community_path ?? '(non choisie)'}`
  return 'Tout le ministère'
})

const promptExcerpt = computed(() => {
  const prompt = wizard.draft.config.system_prompt
  if (!prompt) return null
  return prompt.length > 200 ? `${prompt.slice(0, 200)}…` : prompt
})

function chat(messages: { role: string; content: string }[]) {
  if (!props.agentId) return Promise.reject(new Error('no agent id'))
  return agentsApi.chat(props.agentId, messages)
}
</script>

<template>
  <div class="fr-grid-row fr-grid-row--gutters">
    <div class="fr-col-12">
      <div class="fr-callout">
        <h3 class="fr-callout__title">Récapitulatif de votre agent</h3>
        <dl class="fr-mb-0">
          <dt><strong>Nom :</strong></dt>
          <dd>{{ wizard.draft.config.name || '(non renseigné)' }}</dd>
          <dt class="fr-mt-1w"><strong>Description :</strong></dt>
          <dd>{{ wizard.draft.config.description || '(non renseigné)' }}</dd>
          <dt class="fr-mt-1w"><strong>Visibilité :</strong></dt>
          <dd>{{ visibilityLabel }}</dd>
          <dt class="fr-mt-1w"><strong>Modèle :</strong></dt>
          <dd>{{ wizard.draft.config.model_id }}</dd>
          <dt class="fr-mt-1w"><strong>Prompt système :</strong></dt>
          <dd>{{ promptExcerpt ?? '(non renseigné)' }}</dd>
        </dl>
      </div>
    </div>

    <div class="fr-col-12 fr-col-md-6">
      <h3>Tester l'agent</h3>
      <AgentChatWidget
        v-if="agentId"
        :agent-name="wizard.draft.config.name || 'Agent'"
        :greeting="wizard.draft.config.greeting"
        :send="chat"
      />
      <p v-else class="fr-hint-text">Enregistrez d'abord un brouillon pour pouvoir tester l'agent.</p>
    </div>

    <div class="fr-col-12 fr-col-md-6">
      <h3>Publication</h3>
      <div class="fr-btns-group">
        <button
          type="button"
          class="fr-btn fr-btn--secondary"
          :disabled="!isValid"
          @click="emit('publish', 'draft')"
        >
          Sauvegarder en brouillon
        </button>
        <button
          type="button"
          class="fr-btn"
          :disabled="!isValid"
          @click="emit('publish', 'published')"
        >
          Publier dans mon espace
        </button>
        <button
          type="button"
          class="fr-btn fr-btn--tertiary"
          :disabled="!isValid || wizard.draft.visibility !== 'ministry'"
          :title="
            wizard.draft.visibility !== 'ministry'
              ? 'Disponible uniquement si la visibilité est « Tout le ministère »'
              : undefined
          "
          @click="emit('publish', 'submitted')"
        >
          Proposer au catalogue
        </button>
      </div>
      <p v-if="!isValid" class="fr-text--sm fr-mt-2w">
        Remplissez au moins le <strong>nom</strong> (étape 1) et les
        <strong>instructions système</strong> (étape 2) pour pouvoir publier.
      </p>
    </div>
  </div>
</template>

// apps/next/app/agents/new/_components/step-test-publish.tsx
// Étape 4 — Test et publication (§3.1).
// Les 3 boutons de publication persistent l'agent en base via POST /api/ab/agents
// (stockage Prisma, pas encore d'intégration OpenWebUI). Sur succès, redirect
// vers /agents avec un paramètre d'état affiché en bannière.

'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useWizard } from '../_context';

type PublishStatus = 'draft' | 'published' | 'submitted';

export function StepTestPublish() {
  const router = useRouter();
  const { draft } = useWizard();
  const [busy, setBusy] = useState<null | PublishStatus>(null);
  const [error, setError] = useState<string | null>(null);

  const isValid = draft.name.trim().length > 0 && draft.systemPrompt.trim().length > 0;

  async function save(status: PublishStatus) {
    if (!isValid) {
      setError("Le nom et les instructions système sont obligatoires (étapes 1 et 2).");
      return;
    }
    setBusy(status);
    setError(null);
    try {
      const res = await fetch('/api/ab/agents', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...draft, status }),
      });
      if (!res.ok) {
        const detail = await res.json().catch(() => ({}));
        setError(detail.message ?? `Erreur ${res.status} : ${detail.error ?? 'inconnue'}`);
        setBusy(null);
        return;
      }
      router.push(`/agents?saved=${status}`);
    } catch (err) {
      setError(String(err));
      setBusy(null);
    }
  }

  return (
    <div className="fr-grid-row fr-grid-row--gutters">
      {/* Récapitulatif */}
      <div className="fr-col-12">
        <div className="fr-callout">
          <h3 className="fr-callout__title">Récapitulatif de votre agent</h3>
          <dl className="fr-mb-0">
            <dt>
              <strong>Nom :</strong>
            </dt>
            <dd>{draft.name || <em>(non renseigné)</em>}</dd>
            <dt className="fr-mt-1w">
              <strong>Description :</strong>
            </dt>
            <dd>{draft.description || <em>(non renseigné)</em>}</dd>
            <dt className="fr-mt-1w">
              <strong>Visibilité :</strong>
            </dt>
            <dd>
              {draft.visibility === 'private' && 'Privé'}
              {draft.visibility === 'community' &&
                `Communauté ${draft.communityPath ?? '(non choisie)'}`}
              {draft.visibility === 'ministry' && 'Tout le ministère'}
            </dd>
            <dt className="fr-mt-1w">
              <strong>Modèle :</strong>
            </dt>
            <dd>{draft.modelId}</dd>
            <dt className="fr-mt-1w">
              <strong>Prompt système :</strong>
            </dt>
            <dd>
              {draft.systemPrompt ? (
                `${draft.systemPrompt.slice(0, 200)}${draft.systemPrompt.length > 200 ? '…' : ''}`
              ) : (
                <em>(non renseigné)</em>
              )}
            </dd>
          </dl>
        </div>
      </div>

      <div className="fr-col-12 fr-col-md-6">
        <h3>
          Prévisualisation{' '}
          <span className="fr-badge fr-badge--warning fr-badge--sm">En construction</span>
        </h3>
        {/* Texte destiné à l'utilisateur : on parle de « Mon assistant », jamais
            du nom technique du socle. Un brouillon n'est pas poussé dans Mon
            assistant (cf. POST /api/ab/agents) : seul un agent publié s'y teste. */}
        <div className="fr-callout">
          <p className="fr-callout__text">
            La conversation de test avec l&apos;agent, directement sur cette page, n&apos;est
            pas encore disponible. Pour l&apos;instant, publiez l&apos;agent puis testez-le dans
            Mon assistant, ou utilisez « Utiliser rapidement ici » depuis la liste de vos
            agents (fonctionne aussi pour un brouillon).
          </p>
        </div>
      </div>

      <div className="fr-col-12 fr-col-md-6">
        <h3>Publication</h3>
        <div className="fr-btns-group">
          <button
            type="button"
            className="fr-btn fr-btn--secondary"
            disabled={busy !== null || !isValid}
            onClick={() => save('draft')}
          >
            {busy === 'draft' ? 'Sauvegarde…' : 'Sauvegarder en brouillon'}
          </button>
          <button
            type="button"
            className="fr-btn"
            disabled={busy !== null || !isValid}
            onClick={() => save('published')}
          >
            {busy === 'published' ? 'Publication…' : 'Publier dans mon espace'}
          </button>
          <button
            type="button"
            className="fr-btn fr-btn--tertiary"
            disabled={busy !== null || !isValid || draft.visibility !== 'ministry'}
            onClick={() => save('submitted')}
            title={
              draft.visibility !== 'ministry'
                ? 'Disponible uniquement si la visibilité est « Tout le ministère »'
                : undefined
            }
          >
            {busy === 'submitted' ? 'Soumission…' : 'Proposer au catalogue'}
          </button>
        </div>
        {!isValid && (
          <p className="fr-text--sm fr-mt-2w" style={{ color: 'var(--text-mention-grey)' }}>
            Remplissez au moins le <strong>nom</strong> (étape 1) et les{' '}
            <strong>instructions système</strong> (étape 2) pour pouvoir publier.
          </p>
        )}
        {error && (
          <div className="fr-alert fr-alert--error fr-alert--sm fr-mt-2w">
            <p>{error}</p>
          </div>
        )}
      </div>
    </div>
  );
}
